[package]
name = "rustc_pattern_analysis"
version = "0.0.0"
edition = "2021"

[dependencies]
# tidy-alphabetical-start
rustc_apfloat = "0.2.0"
rustc_arena = { path = "../rustc_arena" }
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_errors = { path = "../rustc_errors", optional = true }
rustc_fluent_macro = { path = "../rustc_fluent_macro", optional = true }
rustc_hir = { path = "../rustc_hir", optional = true }
rustc_index = { path = "../rustc_index" }
rustc_macros = { path = "../rustc_macros", optional = true }
rustc_middle = { path = "../rustc_middle", optional = true }
rustc_session = { path = "../rustc_session", optional = true }
rustc_span = { path = "../rustc_span", optional = true }
rustc_target = { path = "../rustc_target", optional = true }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
tracing = "0.1"
# tidy-alphabetical-end

[features]
default = ["rustc"]
rustc = [
    "dep:rustc_errors",
    "dep:rustc_fluent_macro",
    "dep:rustc_hir",
    "dep:rustc_macros",
    "dep:rustc_middle",
    "dep:rustc_session",
    "dep:rustc_span",
    "dep:rustc_target",
]
