[package]
name = "test_helpers"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
float_eq = "1.0"
proptest = { version = "0.10", default-features = false, features = ["alloc"] }

[features]
all_lane_counts = []
