[package]
name = "salsa"
version = "0.0.0"
authors = ["Salsa developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/salsa-rs/salsa"
description = "A generic framework for on-demand, incrementalized computation (experimental)"

rust-version.workspace = true

[lib]
name = "salsa"

[dependencies]
indexmap = "2.1.0"
lock_api = "0.4"
tracing = "0.1"
parking_lot = "0.12.1"
rustc-hash = "1.0"
smallvec = "1.0.0"
oorandom = "11"
triomphe = "0.1.11"

salsa-macros = { version = "0.0.0", path = "salsa-macros" }

[dev-dependencies]
diff = "0.1.13"
linked-hash-map = "0.5.6"
rand = "0.8.5"
rand_distr = "0.4.3"
test-log = "0.2.14"
insta = "1.18.0"
