[package]
name = "project-model"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
tracing.workspace = true
rustc-hash = "1.1.0"
cargo_metadata = "0.15.0"
semver = "1.0.14"
anyhow.workspace = true
serde_json.workspace = true
serde.workspace = true
triomphe.workspace = true
la-arena.workspace = true
itertools.workspace = true

# local deps
base-db.workspace = true
cfg.workspace = true
paths.workspace = true
profile.workspace = true
stdx.workspace = true
toolchain.workspace = true

[dev-dependencies]
expect-test = "1.4.0"
