[package]
name = "proc-macro-test"
version = "0.0.0"
publish = false

edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[build-dependencies]
cargo_metadata = "0.18.1"

proc-macro-test-impl = { path = "imp", version = "0.0.0" }

# local deps
toolchain.path = "../../toolchain"

[features]
sysroot-abi = ["proc-macro-test-impl/sysroot-abi"]
