name: CI

on:
  - push
  - pull_request

permissions:
  contents: read

env:
  # Enable backtraces for easier debugging
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        libgccjit_version:
          - { gcc: "libgccjit.so", artifacts_branch: "master" }
          - { gcc: "libgccjit_without_int128.so", artifacts_branch: "master-without-128bit-integers" }
        commands: [
          "--mini-tests",
          "--std-tests",
          # FIXME: re-enable asm tests when GCC can emit in the right syntax.
          # "--asm-tests",
          "--test-libcore",
          "--extended-rand-tests",
          "--extended-regex-example-tests",
          "--extended-regex-tests",
          "--test-successful-rustc --nb-parts 2 --current-part 0",
          "--test-successful-rustc --nb-parts 2 --current-part 1",
        ]

    steps:
    - uses: actions/checkout@v3

    # `rustup show` installs from rust-toolchain.toml
    - name: Setup rust toolchain
      run: rustup show

    - name: Setup rust cache
      uses: Swatinem/rust-cache@v2

    - name: Install packages
      # `llvm-14-tools` is needed to install the `FileCheck` binary which is used for asm tests.
      run: sudo apt-get install ninja-build ripgrep llvm-14-tools

    - name: Download artifact
      run: curl -LO https://github.com/antoyo/gcc/releases/latest/download/gcc-13.deb

    - name: Setup path to libgccjit
      run: |
          sudo dpkg --force-overwrite -i gcc-13.deb
          echo /usr/lib/ > gcc_path

    - name: Set env
      run: |
        echo "LIBRARY_PATH=$(cat gcc_path)" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(cat gcc_path)" >> $GITHUB_ENV
        echo "workspace="$GITHUB_WORKSPACE >> $GITHUB_ENV

    #- name: Cache rust repository
      ## We only clone the rust repository for rustc tests
      #if: ${{ contains(matrix.commands, 'rustc') }}
      #uses: actions/cache@v3
      #id: cache-rust-repository
      #with:
        #path: rust
        #key: ${{ runner.os }}-packages-${{ hashFiles('rust/.git/HEAD') }}

    - name: Build
      run: |
        ./y.sh prepare --only-libcore
        # TODO: remove --features master when it is back to the default.
        ./y.sh build --features master
        # TODO: remove --features master when it is back to the default.
        cargo test --features master
        ./y.sh clean all

    - name: Prepare dependencies
      run: |
        git config --global user.email "user@example.com"
        git config --global user.name "User"
        ./y.sh prepare

    - name: Add more failing tests because the sysroot is not compiled with LTO
      run: cat tests/failing-non-lto-tests.txt >> tests/failing-ui-tests.txt

    - name: Run tests
      run: |
        # TODO: remove --features master when it is back to the default.
        ./y.sh test --features master --release --clean --build-sysroot ${{ matrix.commands }}

  duplicates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python tools/check_intrinsics_duplicates.py

  build_system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test build system
        run: |
          cd build_system
          cargo test
